2025-01-26 16:25:00,175 INFO    MainThread:13676 [wandb_setup.py:_flush():68] Current SDK version is 0.19.4
2025-01-26 16:25:00,175 INFO    MainThread:13676 [wandb_setup.py:_flush():68] Configure stats pid to 13676
2025-01-26 16:25:00,175 INFO    MainThread:13676 [wandb_setup.py:_flush():68] Loading settings from C:\Users\maorb\.config\wandb\settings
2025-01-26 16:25:00,175 INFO    MainThread:13676 [wandb_setup.py:_flush():68] Loading settings from C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb\settings
2025-01-26 16:25:00,176 INFO    MainThread:13676 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-26 16:25:00,176 INFO    MainThread:13676 [wandb_init.py:setup_run_log_directory():624] Logging user logs to C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb\run-20250126_162500-grpev92q\logs\debug.log
2025-01-26 16:25:00,176 INFO    MainThread:13676 [wandb_init.py:setup_run_log_directory():625] Logging internal logs to C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb\run-20250126_162500-grpev92q\logs\debug-internal.log
2025-01-26 16:25:00,176 INFO    MainThread:13676 [wandb_init.py:init():743] calling init triggers
2025-01-26 16:25:00,176 INFO    MainThread:13676 [wandb_init.py:init():748] wandb.init called with sweep_config: {}
config: {'model_name': 'catboost', 'val_size': 0.2, 'learning_rate': 0.03, 'iterations': 1000, 'class_weights': [1, 10]}
2025-01-26 16:25:00,176 INFO    MainThread:13676 [wandb_init.py:init():776] starting backend
2025-01-26 16:25:00,388 INFO    MainThread:13676 [wandb_init.py:init():780] sending inform_init request
2025-01-26 16:25:00,458 INFO    MainThread:13676 [wandb_init.py:init():795] backend started and connected
2025-01-26 16:25:00,459 INFO    MainThread:13676 [wandb_init.py:init():888] updated telemetry
2025-01-26 16:25:00,497 INFO    MainThread:13676 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-01-26 16:25:00,845 ERROR   MainThread:13676 [wandb_init.py:init():944] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity tel-aviv-university-org not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-01-26 16:25:00,845 ERROR   MainThread:13676 [wandb_init.py:init():1454] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 1444, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 950, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity tel-aviv-university-org not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-01-26 16:25:00,864 WARNING MsgRouterThr:13676 [router.py:message_loop():75] message_loop has been closed
