2025-01-26 16:12:05,056 INFO    MainThread:41740 [wandb_setup.py:_flush():68] Current SDK version is 0.19.4
2025-01-26 16:12:05,056 INFO    MainThread:41740 [wandb_setup.py:_flush():68] Configure stats pid to 41740
2025-01-26 16:12:05,056 INFO    MainThread:41740 [wandb_setup.py:_flush():68] Loading settings from C:\Users\maorb\.config\wandb\settings
2025-01-26 16:12:05,056 INFO    MainThread:41740 [wandb_setup.py:_flush():68] Loading settings from C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb\settings
2025-01-26 16:12:05,056 INFO    MainThread:41740 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-26 16:12:05,056 INFO    MainThread:41740 [wandb_init.py:setup_run_log_directory():624] Logging user logs to C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb\run-20250126_161205-sowq3nog\logs\debug.log
2025-01-26 16:12:05,071 INFO    MainThread:41740 [wandb_init.py:setup_run_log_directory():625] Logging internal logs to C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb\run-20250126_161205-sowq3nog\logs\debug-internal.log
2025-01-26 16:12:05,071 INFO    MainThread:41740 [wandb_init.py:init():743] calling init triggers
2025-01-26 16:12:05,071 INFO    MainThread:41740 [wandb_init.py:init():748] wandb.init called with sweep_config: {}
config: {'model_name': 'catboost', 'val_size': 0.2, 'learning_rate': 0.03, 'iterations': 1000, 'class_weights': [1, 10]}
2025-01-26 16:12:05,071 INFO    MainThread:41740 [wandb_init.py:init():776] starting backend
2025-01-26 16:12:05,289 INFO    MainThread:41740 [wandb_init.py:init():780] sending inform_init request
2025-01-26 16:12:05,354 INFO    MainThread:41740 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-01-26 16:12:05,361 INFO    MainThread:41740 [wandb_init.py:init():795] backend started and connected
2025-01-26 16:12:05,362 INFO    MainThread:41740 [wandb_init.py:init():888] updated telemetry
2025-01-26 16:12:05,398 INFO    MainThread:41740 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-01-26 16:12:05,789 ERROR   MainThread:41740 [wandb_init.py:init():944] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-26 16:12:05,789 ERROR   MainThread:41740 [wandb_init.py:init():1454] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 1444, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 950, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-26 16:12:05,805 WARNING MsgRouterThr:41740 [router.py:message_loop():75] message_loop has been closed
