13:12:38.980 | [38;5;184mWARNING[0m | preprocess_cat - Still missing values in columns: ['age_level', 'city_development_index', 'var_1', 'user_depth']
13:12:39.026 | [38;5;184mWARNING[0m | preprocess_cat - 3019 rows still have missing 'is_click'. Dropping these rows.
13:13:24.617 | [38;5;184mWARNING[0m | preprocess_cat - Still missing values in columns: 528
13:13:32.724 | [38;5;184mWARNING[0m | root - Truncating wandb.Table object to 200000 rows.
13:13:41.501 | [38;5;184mWARNING[0m | root - Truncating wandb.Table object to 200000 rows.
13:13:50.558 | [38;5;184mWARNING[0m | root - Truncating wandb.Table object to 200000 rows.
13:14:00.642 | [38;5;184mWARNING[0m | root - Truncating wandb.Table object to 200000 rows.
13:14:12.763 | [38;5;184mWARNING[0m | root - Truncating wandb.Table object to 200000 rows.
13:14:25.323 | [38;5;184mWARNING[0m | root - Truncating wandb.Table object to 200000 rows.
13:14:27.327 | [36mINFO[0m    | Task run 'preprocess_data-605' - Finished in state [32mCompleted[0m()
[32m[I 2025-01-28 13:14:27,916][0m A new study created in memory with name: no-name-8673729d-ec7b-489f-baba-555aa264a1ed[0m
[32m[I 2025-01-28 13:15:58,896][0m Trial 0 finished with value: 0.1441319474072019 and parameters: {'depth': 4, 'learning_rate': 0.11357796143028745, 'l2_leaf_reg': 16.77171427983765, 'random_strength': 0.8109464248254362, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6457317795105596}. Best is trial 0 with value: 0.1441319474072019.[0m
[34m[1mwandb[0m: [33mWARNING[0m A graphql request initiated by the public wandb API timed out (timeout=19 sec). Create a new API with an integer timeout larger than 19, e.g., `api = wandb.Api(timeout=29)` to increase the graphql timeout.
[32m[I 2025-01-28 13:17:15,126][0m Trial 1 finished with value: 0.14441433727824074 and parameters: {'depth': 4, 'learning_rate': 0.13349071032579884, 'l2_leaf_reg': 34.25321557780461, 'random_strength': 1.0381793691784813, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 1 with value: 0.14441433727824074.[0m
[32m[I 2025-01-28 13:17:42,662][0m Trial 2 finished with value: 0.1432331966864237 and parameters: {'depth': 4, 'learning_rate': 0.12130818304764913, 'l2_leaf_reg': 18.109254154958236, 'random_strength': 0.4009629138874904, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'min_data_in_leaf': 7}. Best is trial 1 with value: 0.14441433727824074.[0m
[33m[W 2025-01-28 13:17:45,953][0m Trial 3 failed with parameters: {'depth': 4, 'learning_rate': 0.11515135340533607, 'l2_leaf_reg': 18.80829959927818, 'random_strength': 0.7719921911747195, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'min_data_in_leaf': 3} because of the following error: KeyboardInterrupt('').[0m
Traceback (most recent call last):
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\train.py", line 87, in objective
    model.fit(
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\catboost\core.py", line 5245, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, graph, sample_weight, None, None, None, None, baseline, use_best_model,
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\catboost\core.py", line 2410, in _fit
    self._train(
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\catboost\core.py", line 1790, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 5017, in _catboost._CatBoost._train
  File "_catboost.pyx", line 5066, in _catboost._CatBoost._train
KeyboardInterrupt
[33m[W 2025-01-28 13:17:45,960][0m Trial 3 failed with value None.[0m
13:17:45.961 | [38;5;160mERROR[0m   | Task run 'tune_hyperparameters-841' - Crash detected! Execution was aborted by an interrupt signal.
13:17:45.965 | [38;5;160mERROR[0m   | Task run 'tune_hyperparameters-841' - Finished in state [91mCrashed[0m('Execution was aborted by an interrupt signal.')
13:17:45.968 | [38;5;160mERROR[0m   | Flow run[35m 'noisy-armadillo'[0m - Crash detected! Execution was aborted by an interrupt signal.
13:17:46.297 | [38;5;160mERROR[0m   | Flow run[35m 'noisy-armadillo'[0m - Finished in state [91mCrashed[0m('Execution was aborted by an interrupt signal.')
Traceback (most recent call last):
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb_test2.py", line 186, in <module>
    preprocess_and_train_flow(
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flows.py", line 1392, in __call__
    return run_flow(
           ^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 1511, in run_flow
    ret_val = run_flow_sync(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 1354, in run_flow_sync
    engine.call_flow_fn()
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\flow_engine.py", line 766, in call_flow_fn
    result = call_with_parameters(self.flow.fn, self.parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\utilities\callables.py", line 208, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb_test2.py", line 163, in preprocess_and_train_flow
    best_params = tune_hyperparameters(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\tasks.py", line 1035, in __call__
    return run_task(
           ^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\task_engine.py", line 1576, in run_task
    return run_task_sync(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\task_engine.py", line 1387, in run_task_sync
    engine.call_task_fn(txn)
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\task_engine.py", line 828, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\prefect\utilities\callables.py", line 208, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\wandb_test2.py", line 84, in tune_hyperparameters
    return trainer.hyperparameter_tuning(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\train.py", line 130, in hyperparameter_tuning
    study.optimize(objective, n_trials=n_trials)
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\optuna\study\study.py", line 475, in optimize
    _optimize(
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\optuna\study\_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\optuna\study\_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\optuna\study\_optimize.py", line 248, in _run_trial
    raise func_err
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\train.py", line 87, in objective
    model.fit(
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\catboost\core.py", line 5245, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, graph, sample_weight, None, None, None, None, baseline, use_best_model,
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\catboost\core.py", line 2410, in _fit
    self._train(
  File "C:\Users\maorb\Classes\Classical_ML\YDATA-kaggle-assignment\venv\Lib\site-packages\catboost\core.py", line 1790, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 5017, in _catboost._CatBoost._train
  File "_catboost.pyx", line 5066, in _catboost._CatBoost._train
KeyboardInterrupt
